### ISSUE TITLE
Add option to be able to emulate Xcode builds on Windows

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#378]
I am mostly thinking for debugging purposes, but to generate Xcode projects on Windows would help check cross platform features quicker, as the other build modes can be used on Windows.

I think the changes would require
1) Clang meta changes to set up LastUpgradeCheck, SDK and MinimumVersionSupported.
2) C.DefaultToolchain changes (probably a command line option) to ignore platform filters, so that Clang is available on Windows.

**Comment by markfinal** [comment]
Is part of https://github.com/markfinal/BuildAMation/commit/774ff20c81f8eb856c399ed1a1f19f71d9fdc9ee

**Comment by markfinal** [comment]
This no longer works in the latest code.

For example, in Test2:

`bam -b=Xcode -c --C.discoveralltoolchains --C.toolchain=Clang`

errors with

```
(Bam.Core.RunExecutableException) Failed while trying to run 'xcodebuild -showsdks' because The system cannot find the file specified

   at Bam.Core.OSUtilities.RunExecutable(String executable, String arguments) in C:\dev\BuildAMation\Bam.Core\OSUtilities.cs:line 249
   at ClangCommon.ConfigureUtilities.GetValidSDKs(StringArray expectedSDKs) in C:\dev\BuildAMation\packages\ClangCommon\bam\Scripts\ConfigureUtilities.cs:line 108

(Bam.Core.Exception) Unable to locate developer SDKs. Is Xcode installed?
```
