### ISSUE TITLE
VSSolution project file writing IO error

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#428]
This is a curious error that I was not expecting to ever see. What are the chances of getting a temporary filename that collides with an existing temp file?

```
ERROR: (Bam.Core.Exception) Post-build error:
ERROR: (System.IO.IOException) The file exists.

ERROR:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at VSSolutionBuilder.VSSolutionMeta.WriteXMLIfDifferent(String targetPath, XmlWriterSettings settings, XmlDocument document) in c:\dev\BuildAMation\packages\VSSolutionBuilder\bam\Scripts\VSSolutionMet
a.cs:line 95
   at VSSolutionBuilder.VSSolutionMeta.PostExecution() in c:\dev\BuildAMation\packages\VSSolutionBuilder\bam\Scripts\VSSolutionMeta.cs:line 152
```

**Comment by markfinal** [comment]
According to https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx, this can happen if 

The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.

The GetTempFileName method will raise an IOException if no unique temporary file name is available. To resolve this error, delete all unneeded temporary files.
