### ISSUE TITLE
Should we be shipping the vswhere Nuget?

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#459]
The VisualCCommon MetaData class uses it, and references the BAM NuGetPackage directory, but this isn't shipped.

**Comment by markfinal** [comment]
Certainly seems to be the case; tried a local release build:

```
D:\dev\BuildAMation-v1.2.0-AnyCPU\BuildAMation\tests\Test2>bam -b=Native --Visua
lC.version=15.0 -c
BuildAMation (Bam) v1.2.0 (c) Mark Final, 2010-2018. Licensed under BSD 3-clause
. See License.md.
Parts of this software are licensed under the Microsoft Limited Public License (
MS-PL). See MS-PL.md.
Querying package repositories...
Compiling package assembly, CLR 4.0.30319.42000, targetting .NET Framework 4.5,
because no previously compiled package assembly exists.
Creating modules...
ERROR: (Bam.Core.Exception) An error occurred creating top-level modules in name
space 'Test2':
ERROR: (Bam.Core.ModuleCreationException) Error creating module
ERROR: (System.Reflection.TargetInvocationException) Exception has been thrown b
y the target of an invocation.
ERROR: (Bam.Core.Exception) Unable to locate NuGet package for vswhere.2.4.1 at
D:\dev\BuildAMation-v2.1.0-AnyCPU\BuildAMation\NuGetPackages\vswhere.2.4.1
ERROR:
   at VisualCCommon.MetaData.findvswhere()
   at VisualCCommon.MetaData.C.IToolchainDiscovery.discover(Nullable`1 depth)
   at VisualCCommon.LibrarianBase..ctor(EBit depth)

Build Failed
```
