### ISSUE TITLE
Unhandled exception stack trace listed twice

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#7]
For example

Unhandled Exception:
System.IO.DirectoryNotFoundException: Directory '/Users/mark/dev/bam-qt/packages' not found.
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectories (System.String path, System.String searchPattern) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectoriesRecurse (System.String path, System.String searchPattern, System.Collections.Generic.List`1 all) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectories (System.String path, System.String searchPattern, SearchOption searchOption) [0x00000] in <filename unknown>:0
  at Bam.Core.PackageUtilities.IdentifyMainAndDependentPackages (Boolean resolveToSinglePackageVersion, Boolean allowUndefinedPackages) [0x00000] in <filename unknown>:0
  at Bam.Core.PackageUtilities.CompilePackageAssembly () [0x00000] in <filename unknown>:0
  at Bam.Core.EntryPoint.Execute (Bam.Core.Array`1 environments, System.Reflection.Assembly packageAssembly) [0x00000] in <filename unknown>:0
  at Bam.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Directory '/Users/mark/dev/bam-qt/packages' not found.
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectories (System.String path, System.String searchPattern) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectoriesRecurse (System.String path, System.String searchPattern, System.Collections.Generic.List`1 all) [0x00000] in <filename unknown>:0
  at System.IO.Directory.GetDirectories (System.String path, System.String searchPattern, SearchOption searchOption) [0x00000] in <filename unknown>:0
  at Bam.Core.PackageUtilities.IdentifyMainAndDependentPackages (Boolean resolveToSinglePackageVersion, Boolean allowUndefinedPackages) [0x00000] in <filename unknown>:0
  at Bam.Core.PackageUtilities.CompilePackageAssembly () [0x00000] in <filename unknown>:0
  at Bam.Core.EntryPoint.Execute (Bam.Core.Array`1 environments, System.Reflection.Assembly packageAssembly) [0x00000] in <filename unknown>:0
  at Bam.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by markfinal** [comment]
This duplicate listing appears to be Mono specific, as on Windows it shows

$ bam -b=Native --C.toolchain=VisualC

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\dev\bam-qt\packages'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption, Boolean checkHost)
   at System.IO.Directory.InternalGetDirectories(String path, String searchPattern, SearchOption searchOption)
   at Bam.Core.PackageUtilities.IdentifyMainAndDependentPackages(Boolean resolveToSinglePackageVersion, Boolean allowUndefinedPackages) in d:\dev\BuildAMation\Bam.Core\Package\PackageUtilities.cs:line 210
   at Bam.Core.PackageUtilities.CompilePackageAssembly() in d:\dev\BuildAMation\Bam.Core\Package\PackageUtilities.cs:line 350
   at Bam.Core.EntryPoint.Execute(Array`1 environments, Assembly packageAssembly) in d:\dev\BuildAMation\Bam.Core\EntryPoint.cs:line 53
   at Bam.Program.Main(String[] args) in d:\dev\BuildAMation\Bam\Program.cs:line 132

(Windows 8)
Although on Windows 7, the bam process ended with signal 67.
