### ISSUE TITLE
Help and clean command line options are incompatible

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#88]
This is the result:

$ bam -b=VSSolution --C.toolchain=VisualC -j=0 -c --help
BuildAMation (Bam) v1.0.0 (c) Mark Final, 2010-2015. Licensed under BSD 3-clause. See License file.
Using C# compiler v4.0 with assemblies in c:\dev\BuildAMation\bin\Release

Syntax:
    bam [[option[=value]]...]

Deleting build root 'C:\Users\mark\AppData\Local\Temp\'
System.UnauthorizedAccessException not handled: Access to the path 'Director-655e7ac-right.cs' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Bam.Core.PackageUtilities.CompilePackageAssembly(Boolean enforceBamAssemblyVersions)
   at Bam.CommandLineArgumentHelper.PrintHelp()
   at Bam.Program.Main(String[] args)

**Comment by markfinal** [comment]
Specifically, this is when --help -c is invoked in a package directory.
