### ISSUE TITLE
No useful error message when the package definition file does not match the schema

### ISSUE THREAD

**Issue by markfinal** [markfinal/BuildAMation#92]
All the error report is this, with no details, or line numbers

ERROR: (Bam.Core.Exception) An error occurred while reading a package or package definition file '<package definition file path>' does not satisfy any of the package definition schemas
ERROR:
   at Bam.Core.PackageDefinition.Read(Boolean validateSchemaLocation, Boolean validatePackageLocations, Boolean enforceBamAssemblyVersions)
   at Bam.Core.PackageUtilities.GetMasterPackage(Boolean enforceBamAssemblyVersions)
   at Bam.Core.PackageUtilities.IdentifyAllPackages(Boolean allowDuplicates, Boolean enforceBamAssemblyVersions)
   at Bam.DebugProject.Create()
   at Bam.Program.Main(String[] args)

To reproduce, just add this to a package definition file

    </Package>

in the Dependents element.

**Comment by markfinal** [comment]
Forthcoming changes modify the output to look like this:

$ bam --showdefinition
ERROR: (Bam.Core.Exception) Error while reading c:\dev\BuildAMation\tests\Test2\bam\Test2.xml
ERROR: (System.Xml.XmlException) The 'Dependents' start tag on line 4 position 4 does not match the end tag of 'Package'. Line 19, position 7.
ERROR:
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XsdValidatingReader.Read()
   at Bam.Core.PackageDefinition.ReadDependents(XmlReader xmlReader, Boolean validatePackageLocations) in c:\dev\BuildAMation\Bam.Core\Package\Package
Definition.cs:line 549
   at Bam.Core.PackageDefinition.ReadCurrent(XmlReaderSettings readerSettings, Boolean validateSchemaLocation, Boolean validatePackageLocations, Boole
an enforceBamAssemblyVersions) in c:\dev\BuildAMation\Bam.Core\Package\PackageDefinition.cs:line 834
